name: IC - Compilation et publication du matériel

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Installation de Sphinx
      run: pip install sphinx==8.1.3 sphinx-intl sphinx-book-theme==1.1.3

    - name: Compilation de la version française
      run: sphinx-build doc/fr doc/_build/fr

    - name: Compilation de la version anglaise
      run: sphinx-build doc/en doc/_build/en

    - name: Ajouter la redirection automatique
      run: cp doc/redirect.html doc/_build/index.html

    - name: Déploiement
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: doc/_build/
        force_orphan: true
